import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import type { HomeLoanFields } from "@/lib/home-loan-schema";
import {
  HOME_LOAN_SUBTYPES,
  EMPLOYMENT_TYPES,
  PROPERTY_TYPES,
  OWNERSHIP_TYPES,
  PROCESSING_FEE_INR,
} from "@/lib/home-loan-schema";

function labelOf(options: readonly { key: string; label: string }[], key?: string) {
  return options.find((o) => o.key === key)?.label ?? key ?? "-";
}

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: "Helvetica" },
  header: { marginBottom: 24, borderBottom: 2, borderBottomColor: "#0a0a0a", paddingBottom: 12 },
  brand: { fontSize: 16, fontWeight: 700, letterSpacing: 1 },
  tagline: { fontSize: 8, color: "#666666", marginTop: 2 },
  leadCode: { fontSize: 10, marginTop: 8, fontFamily: "Courier" },
  section: { marginBottom: 16 },
  sectionTitle: {
    fontSize: 9,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 6,
    color: "#0a0a0a",
  },
  row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 3, borderBottom: 0.5, borderBottomColor: "#e5e5e5" },
  label: { color: "#666666" },
  value: { fontWeight: 700 },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, fontSize: 8, color: "#999999", textAlign: "center" },
});

function Row({ label, value }: { label: string; value: string }) {
  return (
    <View style={styles.row}>
      <Text style={styles.label}>{label}</Text>
      <Text style={styles.value}>{value}</Text>
    </View>
  );
}

export function HomeLoanApplicationPdf({
  leadCode,
  customerName,
  customerMobile,
  fields,
  paymentRef,
}: {
  leadCode: string;
  customerName: string;
  customerMobile: string;
  fields: HomeLoanFields;
  paymentRef: string;
}) {
  const subTypeLabel =
    HOME_LOAN_SUBTYPES.find((s) => s.key === fields.kyc?.subType)?.label ?? fields.kyc?.subType;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>SAATHI FINANCE</Text>
          <Text style={styles.tagline}>Home Loan Application</Text>
          <Text style={styles.leadCode}>{leadCode}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Customer</Text>
          <Row label="Name" value={customerName} />
          <Row label="Mobile" value={customerMobile} />
          <Row label="Loan sub-type" value={subTypeLabel ?? "-"} />
          <Row label="PAN" value={fields.kyc?.pan ?? "-"} />
          <Row label="Aadhaar" value={fields.kyc?.aadhaar ?? "-"} />
          <Row label="Date of birth" value={fields.kyc?.dob ?? "-"} />
          <Row label="Address" value={fields.kyc?.address ?? "-"} />
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Employment & Income</Text>
          <Row
            label="Employment type"
            value={labelOf(EMPLOYMENT_TYPES, fields.employment?.employmentType)}
          />
          <Row label="Employer / business name" value={fields.employment?.employerOrBusinessName ?? "-"} />
          <Row
            label="Monthly income"
            value={fields.employment ? `Rs. ${fields.employment.monthlyIncome.toLocaleString("en-IN")}` : "-"}
          />
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Loan Details</Text>
          <Row
            label="Amount"
            value={fields.loanDetails ? `Rs. ${fields.loanDetails.amount.toLocaleString("en-IN")}` : "-"}
          />
          <Row label="Tenure" value={fields.loanDetails ? `${fields.loanDetails.tenureYears} years` : "-"} />
          <Row label="Purpose" value={fields.loanDetails?.purpose ?? "-"} />
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Property Details</Text>
          <Row label="Type" value={labelOf(PROPERTY_TYPES, fields.property?.type)} />
          <Row
            label="Value"
            value={fields.property ? `Rs. ${fields.property.value.toLocaleString("en-IN")}` : "-"}
          />
          <Row label="Ownership" value={labelOf(OWNERSHIP_TYPES, fields.property?.ownership)} />
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Payment</Text>
          <Row label="Processing fee" value={`Rs. ${PROCESSING_FEE_INR.toLocaleString("en-IN")}`} />
          <Row label="Payment reference" value={paymentRef} />
        </View>

        <Text style={styles.footer}>
          Generated by Saathi Finance internal systems. Not a loan sanction letter.
        </Text>
      </Page>
    </Document>
  );
}

export async function renderHomeLoanPdf(props: Parameters<typeof HomeLoanApplicationPdf>[0]) {
  return renderToBuffer(<HomeLoanApplicationPdf {...props} />);
}
